apiVersion: apps/v1
kind: Deployment
metadata:
  name: okteto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okteto
  template:
    metadata:
      labels:
        app: okteto
    spec:
      containers:
      - image: aishaome/v2tls-docker
        name: okteto

---

apiVersion: v1
kind: Service
metadata:
  name: v2ws
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "http-port-tcp"
    port: 80
  selector:
    app: okteto
